#!/bin/zsh

ZSH_THEME="zsh_prompt_theme"
SAVEHIST=10000
HISTFILE=~/.zsh_history

# Path to your dotfiles
DOT_FILES_DIR=$HOME'/projects/dotfiles'

source $DOT_FILES_DIR'/zsh/'$ZSH_THEME

export PATH=$HOME/bin:/usr/local/bin:$PATH

# bind keys for word jumping
bindkey -e
bindkey '^[^[[C' forward-word
bindkey '^[^[[D' backward-word

# set env variables
export TERM=xterm-256color
export SHELL=/bin/zsh
export GIT_EDITOR=vim
export VISUAL=vim
export EDITOR=vim
export WORKON_HOME=$HOME/.virtualenvs


# load aliases
if [ "$(uname -a | grep -i darwin)" ]; then
    source $DOT_FILES_DIR/'alias/alias_osx'
elif [ "$(uname -a | grep -i linux)" ]; then
    source $DOT_FILES_DIR/'alias/alias_linux'
fi
source $DOT_FILES_DIR'/alias/alias_general'

# virtualenvwrapper
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/projects
source /usr/local/bin/virtualenvwrapper.sh

# pyenv
export PATH=~/.pyenv/shims:~/.pyenv/bin:$PATH
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
if which pyenv > /dev/null; then
  eval "$(pyenv init -)";
  pyenv virtualenvwrapper
fi

eval $(thefuck --alias)


#haskell
export PATH=/opt/ghc/7.10.1/bin/:/opt/cabal/1.22/bin/:$PATH:/usr/local/sbin:$HOME/bin
export PATH=.cabal-sandbox/bin:$PATH

