#!/bin/zsh

ZSH_THEME="zsh_prompt_theme"

# Path to your dotfiles
DOT_FILES_DIR=$HOME'/.config/dotfiles'

# Path to your oh-my-zsh installation
export ZSH=$DOT_FILES_DIR'/oh-my-zsh'

source $DOT_FILES_DIR'/zsh/'$ZSH_THEME

# User configuration
export PATH=$HOME/bin:/usr/local/bin:$PATH

# bind keys for word jumping
bindkey -e
bindkey '^[^[[C' forward-word
bindkey '^[^[[D' backward-word

# set env variables
export TERM=xterm-256color
export SHELL=/bin/zsh
export GIT_EDITOR=vim
export VISUAL=vim
export EDITOR=vim
export WORKON_HOME=$HOME/.virtualenvs


# load aliases
if [ "$(uname -a | grep -i darwin)" ]; then
    source $DOT_FILES_DIR/'alias/alias_osx'
elif [ "$(uname -a | grep -i linux)" ]; then
    source $DOT_FILES_DIR/'alias/.alias_linux'
fi
source $DOT_FILES_DIR'/alias/alias_general'


source /usr/local/bin/virtualenvwrapper.sh